languages:
  JavaScript: true
ratings:
  paths:
  - "src/**/*.js"
exclude_paths:
- "spec/**/*.js"
- "lib/**"
- "dist/*"
- "grunt/**"
- "images/*"
- "**/*.md"
- "**/*.yml"
- "**/*.json"
- "**/*.scss"
- "**/*.erb"
- "*.sh"
